server:
  port: 8080

spring:
  application:
    name: customer
  datasource:
    password: postgres
    url: jdbc:postgresql://localhost:5432/mytestdb
    username: postgres
    driver: org.postgresql.Driver

eureka:
  client:
    server-url:
     defaultZone: http://localhost:8761/

