server:
  port: 8082

spring:
  application:
    name: notification
  datasource:
    password: pass
    url: jdbc:postgresql://localhost:5430/mynotificatedb
    username: anton
    driver: org.postgresql.Driver
  mail:
    mailfrom: filfilfillipliplip@gmail.com
    frompass: 329297929z

eureka:
  client:
    server-url:
      defaultZone: http://localhost:8761/


