server:
  port: 8081
spring:
  application:
    name: fraud
  datasource:
    password: pass
    url: jdbc:postgresql://localhost:5433/frauderdb
    username: anton
    driver: org.postgresql.Driver

eureka:
  client:
    server-url:
      defaultZone: http://localhost:8761/

