server:
  port: 8082

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false

spring:
  application:
    name: eurika
  datasource:
    password: postgres
    url: jdbc:postgresql://localhost:5432/mytestdb
    username: postgres
    driver: org.postgresql.Driver
